# Generated by Django 3.0 on 2019-12-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
