# Generated by Django 3.0 on 2019-12-17 10:10

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('gal', '0003_auto_20191217_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
